name: glasses
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # for localizations => https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  # for environments => https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.1.0
  # for svg => https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1
  # for dependency injection => https://pub.dev/packages/get_it
  get_it: ^7.7.0
  # for shimmer effect => https://pub.dev/packages/shimmer
  shimmer: ^3.0.0
  # for caching images => https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.0
  # for routing => https://pub.dev/packages/auto_route
  auto_route: ^9.2.0

  # for responsibility => https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3

  json_annotation: ^4.9.0
  # for creating api models => https://pub.dev/packages/json_annotation
  freezed_annotation: ^2.4.4
  # for network requests => https://pub.dev/packages/dio
  dio: ^5.5.0+1

  flutter_bloc: ^8.1.6
  # for slider banner => https://pub.dev/packages/carousel_slider
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # auto_route generator => https://pub.dev/packages/auto_route_generator
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  # for creating api models => https://pub.dev/packages/json_serializable
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
